### ISSUE TITLE
Confused with the API

### ISSUE THREAD

**Issue by manotejmeka** [LeanKit/LeanKit.API.Client#10]
How can I get the tiles and the Id's of the other lanes other than Backlogs and Archives lanes?

Sorry this is not an issue with the code, just wanted to know how to get that functionality.

**Comment by reverentgeek** [comment]
You can retrieve the entire board using `GetBoard(id)`, and the returned object includes the collections `Lanes` (active lanes), `Backlog`, and `Archive`. You can get the Id's and Titles of each of the lanes on the board from these collections.

To make it easier, you can combine all three collections into a single list using LINQ. For example:

```
var board = api.GetBoard(boardId);
var allLanes = new List<Lane>().Concat(Backlog).Concat(Lanes).Concat(Archive);
```

Hope this helps!

**Comment by manotejmeka** [comment]
Thank you for that help. I am reaching into one more problem. I am trying to add cards to my board to a specific lane. I see that their is a function called 
```
CardAddResult AddCard(long boardId, Card newCard
```
 I have the boardId also I created a new card by saying 
```
Card newCard = new Card();
newCard.Title = "blah";
newCard.LaneId = ###;
newCard.Active = true;
```
and try to add the card though the AddCard function, but it does not appear on the board. I am confused what I might be doing wrong.

**Comment by manotejmeka** [comment]
Thank you for that help. I am reaching into one more problem. I am trying to add cards to my board to a specific lane. I see that their is a function called 
```
CardAddResult AddCard(long boardId, Card newCard
```
 I have the boardId also I created a new card by saying 
```
Card newCard = new Card();
newCard.Title = "blah";
newCard.LaneId = ###;
newCard.Active = true;
```
and try to add the card though the AddCard function, but it does not appear on the board. I am confused what I might be doing wrong.

**Comment by reverentgeek** [comment]
You are probably getting an error message that is, unfortunately, not very descriptive. The thing you are likely missing is the required `TypeId` property. This tells the API what type of card you wish to create. Here's an example in C#.

```csharp
private long TestAddCardToLane(ILeanKitApi api)
{
	const string boardName = "API Test Board";
	const string laneName = "Doing";

	// Get all the boards
	var boards = api.GetBoards();

	// Get the Board ID for the board, change to match your board name
	var boardId = boards.First(x => x.Title.Equals(boardName, StringComparison.OrdinalIgnoreCase)).Id;
	var board = api.GetBoard(boardId);
	// Get the Lane ID for the "Doing" Lane
	var laneId = board.Lanes.First(x => x.Title.Equals(laneName, StringComparison.OrdinalIgnoreCase)).Id.GetValueOrDefault();

	// Get the default Card Type for the board
	var cardType = board.CardTypes.FirstOrDefault(x => x.IsDefault) ?? board.CardTypes[0];
	
	// Create a new Card
	var card = new Card
	{
		Title = "Testing " + DateTime.Now.ToShortTimeString(),
		Description = "A Description",
		TypeId = cardType.Id,
		LaneId = laneId,
		Priority = 1
	};

	// Add it to the board
	var result = api.AddCard(boardId, card);

	// Result should contain the new Card ID
	Console.WriteLine(result.CardId);
	return result.CardId;
}
```
