### ISSUE TITLE
API not updating

### ISSUE THREAD

**Issue by dmportella** [LeanKit/LeanKit.API.Client#5]
Hello I not sure this is a C# api issue but I noticed that tickets/cards are not getting updated I move a ticket or add a comment and the api return a wrong date time for the update exactly a day behind.

I seen discrepancies on the _client.GetCard(board.Id, cardId); and on the Cards available on the response from the Get Board method. they both have different last activity, move and comment from each other.

It was workign yesterday but now the api just seem to return incorrect data.

**Comment by reverentgeek** [comment]
Hi @dmportella,

Yes, the time zone of the account used to access the API does make a difference in the dates of items being retrieved. I will update our documentation to help make that more clear.
