### ISSUE TITLE
GetBoardHistorySince arguments are incorrect

### ISSUE THREAD

**Issue by dmportella** [LeanKit/LeanKit.API.Client#6]
The interface is enforcing the wrong type for board version

It should be a long but instead its using a int.

**Comment by reverentgeek** [comment]
Board version is an integer, not to be confused with the board ID, which is a long. Every board starts at version 1 and increments each time a board is modified in any way.

**Comment by reverentgeek** [comment]
Ah, now I see. The version property on a board is a long. Let me do some more research and get back to you.

**Comment by dmportella** [comment]
cool thats what i meant... the board version id is indeed a long... got me worried at the time i saw

**Comment by reverentgeek** [comment]
I've updated the interfaces throughout. Board version should be consistently referenced as a long.

**Comment by dmportella** [comment]
awesome ! thank you!
