### ISSUE TITLE
GetBoardHistorySince returns broken BoardHistoryEvents

### ISSUE THREAD

**Issue by dmportella** [LeanKit/LeanKit.API.Client#7]
GetBoardHistorySince returns BoardHistoryEvent with EventDateTime always set to datetime min value

EventDateTime is missing the time part makign impossible to know when it happen or even see them in order.

See example below
Important ids haev been changed to 9999's for security reasons
{
    "ReplyData": [
        [
            {
                "CardId": 9999,
                "EventType": "CardMoveEvent",
                "EventDateTime": "20/07/2015",
                "Message": "Daniel Portella moved the Card [(S95) Necromancer Ticket DO NOT DELETE] from Release: Ready to Deploy to Release: Pre-Deploy Huddle.",
                "ToLaneId": 9999,
                "FromLaneId": 9999,
                "RequiresBoardRefresh": false,
                "IsBlocked": false,
                "BlockedComment": null,
                "UserId": 0,
                "AssignedUserId": 0,
                "IsUnassigning": false,
                "CommentText": null,
                "WipOverrideComment": null,
                "WipOverrideLane": 0,
                "WipOverrideUser": 0,
                "TaskboardParentCardId": 0,
                "TaskboardId": 0
            }
        ]
    ],
    "ReplyCode": 200,
    "ReplyText": "Board history since last update successfully retrieved."
}

**Comment by reverentgeek** [comment]
`GetBoardHistorySince` only returns the most recent 5 events since the given board version number, and is therefor not a very reliable way to keep track of all changes that have occurred to a board since the last known version number. `CheckForUpdates` will return all the events that have occurred, including date + time of those events. 

Hope this helps!

**Comment by dmportella** [comment]
ok but shouldnt it return the time too - consistency is important.

but i am glad i will check the CheckForUpdates method and see what it returns.

**Comment by reverentgeek** [comment]
Yes, I agree it should return a date/time for consistency. I also think `GetBoardHistorySince` is not very useful ;)

FYI, I noticed there was an issue parsing dates of events. I've added an overload for the Create() method so you can specify a date format (e.g. "dd/MM/yyyy", "yyyy/MM/dd", or "MM/dd/yyyy"). For example:

```
var api = new LeanKitClientFactory().Create(leanKitAuth, "dd/MM/yyyy");
```

**Comment by dmportella** [comment]
Yeah i was thinking that but didnt want to say anything :) GetBoardHistorySince isnt really useful.

Ok the date on events i noticed it too the json returns the right date but the object has a default date time {01/01/0001 00:00:00} will your fix resolve that?

**Comment by reverentgeek** [comment]
Yes, the latest version should fix the issue where the date/times returned in JSON formatted to the current user's date format were not getting parsed correctly. You will need to specify your date format when creating the API client.

**Comment by dmportella** [comment]
yep I added it and all is working now. I will close this ticket
