### ISSUE TITLE
Card Search not respecting MaxResults changes

### ISSUE THREAD

**Issue by bobrot** [LeanKit/LeanKit.API.Client#8]
When I call SearchCards passing in a SearchOptions object with a higher number of MaxResults, I still only get 20 results (the default) in my result set.

**Comment by reverentgeek** [comment]
Yes, this is correct. Our Search API is currently limited to 20 results, so any `MaxResults` setting over 20 will be ignored. To get more than 20 cards from a search, you must use `Page` to request additional result sets.

**Comment by bobrot** [comment]
Would you consider adding this to your documentation?

**Comment by reverentgeek** [comment]
Thank you for the suggestion. You are right. I've updated the [Search Cards](https://support.leankit.com/hc/en-us/articles/204412963) API documentation to make it more clear about the 20-card limit. Let me know if you have any other recommendations.
